import { clientsClaim, skipWaiting } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { cleanupOutdatedCaches, matchPrecache, precacheAndRoute } from "workbox-precaching";
import { NavigationRoute, registerRoute, setCatchHandler } from "workbox-routing";
import { NetworkFirst, StaleWhileRevalidate } from "workbox-strategies";

declare let self: any;

// Take control immediately
skipWaiting();
clientsClaim();

// Precache all assets generated by the build (injected by vite-plugin-pwa)
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// ──────────────────────────────────────────────
// Runtime caching strategies
// ──────────────────────────────────────────────

// 1. Translation files — StaleWhileRevalidate
// Serve cached translations instantly, update in the background
registerRoute(
  ({ url }) => url.pathname.includes("/locales/"),
  new StaleWhileRevalidate({
    cacheName: "translations-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// 2. Microfrontend Manifests (remoteEntry.js) — NetworkFirst
// Always query network first so we get redeployed MFEs, fallback to cache
registerRoute(
  ({ url }) => url.pathname.endsWith("/remoteEntry.js") || url.pathname.endsWith("/remoteEntry.ssr.js"),
  new NetworkFirst({
    cacheName: "mfe-entries-cache",
    networkTimeoutSeconds: 2,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24, // 1 day
      }),
    ],
  })
);

// 3. Hashed assets and MFE chunk files — StaleWhileRevalidate
// Cache remote JS/CSS assets dynamically
registerRoute(
  ({ url }) => url.pathname.includes("/assets/"),
  new StaleWhileRevalidate({
    cacheName: "mfe-assets-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 150,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// 4. Navigation requests — NetworkFirst with offline fallback
const navigationHandler = new NetworkFirst({
  cacheName: "navigation-cache",
  networkTimeoutSeconds: 3,
});

const navigationRoute = new NavigationRoute(navigationHandler, {
  // Don't handle Firebase auth redirect URLs
  denylist: [/\/__\/auth\//],
});

registerRoute(navigationRoute);

// 5. Offline fallback
setCatchHandler(async ({ request }) => {
  if (request.mode === "navigate") {
    return (await matchPrecache("offline.html")) || (await matchPrecache("/offline.html")) || Response.error();
  }
  return Response.error();
});
