export enum PATH_CONSTRANTS {
    HOME = "/",
    SIGN_IN = "/sign-in",
    SIGN_UP = "/sign-up",
    COMMUNITY = "/community",
    GROUPS = "/community/groups",
    ADD_FRIENDS = "/community/add-friends",
    MY_FRIENDS = "/community/my-friends",
    PAGE_404 = "/404",
    PLANNING = "/planning",
    TODO = "/planning/to-do",
    SHOPPING = "/planning/shopping",
    PRODUCTS = "/planning/products",
    SETTINGS = "/settings",
}
